# options for analysis running
run:
  modules-download-mode: mod
linters-settings:
  funlen:
    lines: 300
    statements: 300
  gocyclo:
    min-complexity: 40
  dupl:
    threshold: 150
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

issues:
  exclude-rules:
    - text: "type `typedDesc` is unused"
      linters:
        - unused
    - text: "rewrite if-else to switch statement"
      linters:
        - gocritic
    - text: "consider giving a name to these results"
      linters:
        - gocritic
    - text: "Subprocess launched with a potential tainted input or cmd arguments"
      linters:
        - gosec
    - text: "if statements should only be cuddled with assignments"
      linters:
        - wsl
    - text: "Error return value of"
      linters:
        errcheck
