version: "2"
run:
  modules-download-mode: mod
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          files:
            - '!**/*_a _file.go'
          allow:
            - $gostd
            - github.com/mjtrangoni/flexlm_exporter
            - github.com/prometheus/client_golang
            - github.com/prometheus/common/promslog
            - github.com/prometheus/common/version
            - github.com/prometheus/exporter-toolkit/web
            - github.com/alecthomas/kingpin/v2
            - gopkg.in/yaml.v3
            - golang.org/x/text/cases
            - golang.org/x/text/language
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    dogsled:
      max-blank-identifiers: 3
    dupl:
      threshold: 150
    funlen:
      lines: 300
      statements: 300
    gocritic:
      disabled-checks:
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 50
    lll:
      line-length: 140
    misspell:
      locale: US
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unused
        text: type `typedDesc` is unused
      - linters:
          - gosec
        text: Subprocess launched with a potential tainted input or cmd arguments
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
