---
version: 2
project_name: flexlm_exporter

before:
  hooks:
    - go mod tidy

builds:
  - binary: "{{ .ProjectName }}"
    id: "{{ .ProjectName }}"
    hooks:
      post: make tarball
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
      - "386"

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy


archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

snapshot:
  version_template: "{{ .Tag }}-snapshot"
