project_name: flexlm_exporter

before:
  hooks:
    - go mod tidy

builds:
  - binary: "{{ .ProjectName }}"
    id: "{{ .ProjectName }}"
    hooks:
      post: make tarball
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
      - 386

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-snapshot"
