go:
    # Whenever the Go version is updated here, go.mod, .github/workflows/build.yml,
    # and .circleci/config.yml should also be updated.
    version: 1.21
    cgo: false
repository:
    path: github.com/mjtrangoni/flexlm_exporter
build:
    binaries:
        - name: flexlm_exporter
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -s
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - darwin/amd64
        - darwin/arm64
        - linux/amd64
        - linux/386
        - windows/amd64
        - windows/386
