---
name: Feature request
description: Suggest an idea for this project.
body:
  - type: textarea
    attributes:
      label: Proposal
      description: Use case. Why is this important?
      placeholder: “Nice to have” is not a good use case. :)
    validations:
      required: true
