---
name: Lint

on: [push, pull_request]

permissions: {}

jobs:
  lint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Validate CircleCI configuration
        run: |
          docker run --rm \
            --volume "$GITHUB_WORKSPACE:/data" \
            --workdir /data \
            docker.io/circleci/circleci-cli@sha256:ac7c180a4bb9099f04a37295e2710bb9c5b74df7b9313358ccbb5dd3da3ab793 \
            config validate /data/.circleci/config.yml
      - name: Super-Linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: true
          VALIDATE_GO_RELEASER: true
